### ISSUE TITLE
Extension not working and error when saving config

### ISSUE THREAD

**Issue by jbriales** [brpaz/ulauncher-cheats#1]
I installed the extension within ulauncher, but it does not work (the "cheats" keyword does not provoke any special behavior).
Besides, if I try to save the settings, e.g. to set the config field Cheats dir, then ulauncher returns an error:
Unexpected API error. KeyError: com.github.brpaz.ulauncher-cheats

**Comment by dominikmanowski** [comment]
I have the same situation - 'Unexpected API error. KeyError: com.github.brpaz.ulauncher-cheats' when saving settings.

**Comment by brpaz** [comment]
Hello. can you try closing Ulauncher and then running it from command line with `ulauncher -v`?
Then paste here the output of the command.

Thank you.

**Comment by killer2alex** [comment]
Hey,
I got the same error-Message with the following terminal-output:
```2018-12-03 16:58:16,634 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_extension_update_prefs() | Update extension preferences: {'pref.cheats_dir': '~/', 'pref.demo_kw': 'cheats', 'pref.use_hawkeye_as_default_action': 'false', 'pref.urls_file': 'urls', 'pref.hawkeye_bin': '/usr/local/bin/hawkeye', 'callback': '__jp3', 'id': 'com.github.brpaz.ulauncher-cheats'}
2018-12-03 16:58:16,634 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. KeyError: com.github.brpaz.ulauncher-cheats
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 160, in on_scheme_callback
    resp = rt.dispatch(self, scheme_request.get_uri())
  File "/usr/lib/python2.7/dist-packages/ulauncher/util/Router.py", line 49, in dispatch
    return callback(context, url_params)
  File "/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 368, in prefs_extension_update_prefs
    controller = ExtensionServer.get_instance().get_controller(ext_id)
  File "/usr/lib/python2.7/dist-packages/ulauncher/api/server/ExtensionServer.py", line 76, in get_controller
    return self.controllers[extension_id]
KeyError: 'com.github.brpaz.ulauncher-cheats'
```

I hope this helps ;-)

**Comment by jbriales** [comment]
I think I found what the issue was:
I installed the extension via Ulauncher settings, which is pretty convenient, but it doesn't take care of dependencies! So I was missing the glob2 package.
I found out when running `ulauncher -v` as it showed an early Traceback error when starting the program, due to the failing `import`.
The output @killer2alex reported (the same I was seeing later on), is due to the extension not being loaded by Ulauncher. Thus, in the Configuration Ulauncher displays all the "installed" extensions but when trying to modify some value in the settings it complains because inside the Ulauncher server there is no such extension.

Written in a rush, but should give the info to find out/fix this kind of issues :)

**Comment by brpaz** [comment]
Sorry for the late reply. 

Yes, that´s a known issue of Ulauncher. Unfortunately, the maximum extension authors can  for now is to try to document the dependencies the best, but installing them will always be a manual process.

I will close this now.
